### ISSUE TITLE
file not found BUG

### ISSUE THREAD

**Issue by xushaun** [wuhx/shelldroid#1]
10-20 22:01:02.947: E/AndroidRuntime(9794): Caused by: java.io.FileNotFoundException: /data/user/0/im.xun.shelldroid/files/ENV_REPO/com.hx.hxonline/33fb5582-2753-4382-8b5b-dae0c2c21cb4/.ENV: open failed: ENOENT (No such file or directory)

Above is the bug report
I install your pre version APK

**Comment by xushaun** [comment]
Can i make a app like your app using Java?

please give me some advice

i want make a app with same funtion you have done with Android Studio

**Comment by wuhx** [comment]
Have  you  grant root permission to  Shelldroid?
SeLinux need to be turn off.

Of course you can rewrite it in Java, it should be more straightforward than Scala.
